CREATE TABLE public.recap_fjcintegrateddatabase (
    id integer NOT NULL,
    date_created timestamp with time zone,
    date_modified timestamp with time zone, 
    dataset_source smallint,
    office varchar(3),
    docket_number varchar(7),
    origin smallint,
    date_filed date,
    jurisdiction smallint,
    nature_of_suit integer,
    title text,
    section varchar(200),
    subsection varchar(200),
    diversity_of_residence smallint,
    class_action boolean,
    monetary_demand integer,
    county_of_residence integer,
    arbitration_at_filing varchar(1),
    arbitration_at_termination varchar(1),
    multidistrict_litigation_docket_number text,
    plaintiff text,
    defendant text,
    date_transfer date,
    transfer_office varchar(3),
    transfer_docket_number text,
    transfer_origin text,
    date_terminated date,
    termination_class_action_status smallint,
    procedural_progress smallint,
    disposition smallint,
    nature_of_judgement smallint,
    amount_received integer,
    judgment smallint,
    pro_se smallint,
    year_of_tape integer,
    nature_of_offense varchar(4),
    version integer,
    circuit_id varchar(15),
    district_id varchar(15)
);

